export default {
  login: "nazreen-siddique",
  id: 114997363,
  node_id: "U_kgDOBtq4cw",
  avatar_url: "https://avatars.githubusercontent.com/u/114997363?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/nazreen-siddique",
  html_url: "https://github.com/nazreen-siddique",
  followers_url: "https://api.github.com/users/nazreen-siddique/followers",
  following_url:
    "https://api.github.com/users/nazreen-siddique/following{/other_user}",
  gists_url: "https://api.github.com/users/nazreen-siddique/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/nazreen-siddique/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/nazreen-siddique/subscriptions",
  organizations_url: "https://api.github.com/users/nazreen-siddique/orgs",
  repos_url: "https://api.github.com/users/nazreen-siddique/repos",
  events_url: "https://api.github.com/users/nazreen-siddique/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/nazreen-siddique/received_events",
  type: "User",
  site_admin: false,
  name: "nazreen siddique",
  company: "-",
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "developer",
  twitter_username: null,
  public_repos: 1,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2022-10-04T11:22:14Z",
  updated_at: "2022-10-08T05:43:15Z",
};